name: Nightly

on:
  schedule:
    - cron: '17 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/release.yml
    with:
      tag: nightly
      source_ref: ${{ github.sha }}
    secrets: inherit
